### ISSUE TITLE
Bug in documentation formatting

### ISSUE THREAD

**Issue by akarelas** [houseabsolute/List-AllUtils#11]
Here: https://metacpan.org/pod/List::AllUtils#sum0

It says: `Similar to "sum", except this returns 0 when given an empty list, rather than undef. =head1 KEY/VALUE PAIR LIST FUNCTIONS`

I think =head1 in the source should have a blank line above it, to make the section heading appear properly. Here: https://metacpan.org/release/List-AllUtils/source/lib/List/AllUtils.pm#L320

**Comment by autarch** [comment]
Thanks, I just pushed a fix for this.
