### ISSUE TITLE
missing Makefile.PL?

### ISSUE THREAD

**Issue by stuart-little** [houseabsolute/List-AllUtils#13]
The [CONTRIBUTING.md file](https://github.com/houseabsolute/List-AllUtils/blob/master/CONTRIBUTING.md#contributing) refers to a `Makefile.PL` in the repo, but one is not present as far as I can tell; after cloning the repo and `cd`-ing to it:
```
$ cpanm .
--> Working on .
Configuring $HOME/repos/List-AllUtils ... N/A
! The distribution doesn't have a proper Makefile.PL/Build.PL See $HOME/.cpanm/work/1622742460.388084/build.log for details.
```
All is well after I run `dzil build` (or `dzil install` for that matter), but the documentation seems to be inaccurate on the `Makefile.PL` thing at the moment.

**Comment by autarch** [comment]
Thanks for the report. I pushed a commit that adds this file.
